export const ActionTypes = {
  FETCH_DATA: "FETCH_DATA",
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  FETCH_RECIPES: "FETCH_RECIPES",
  SELECTED_RECIPE: "SELECTED_RECIPE",
  SELECTED_CLOTH: "SELECTED_CLOTH",
  FETCH_FILTERS: "FETCH_FILTERS",
  SEND_FILTERS: "SEND_FILTERS",
};
